version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      timezone: Asia/Jakarta
    labels:
      - dependencies
    groups:
      dependencies:
        patterns: ['*']

  - package-ecosystem: composer
    directories:
      - /
      - /packages/*
    schedule:
      interval: weekly
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    labels:
      - dependencies

  - package-ecosystem: bun
    directories:
      - /
      - /packages/*
    schedule:
      interval: weekly
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    ignore:
      - dependency-name: '@types/bun'
      - dependency-name: '@types/node'
      - dependency-name: 'typescript'
    groups:
      commitlint:
        patterns: ['@commitlint/*']
        update-types: [patch]
    labels:
      - dependencies
