github_actions:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**.yml'

'pkg: tabellio-cf7':
  - changed-files:
      - any-glob-to-any-file:
          - 'packages/tabellio-cf7/**'

assets:
  - changed-files:
      - any-glob-to-any-file:
          - 'assets/**'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**'

enhancement:
  - changed-files:
      - any-glob-to-any-file: '**'
