name: Release

on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    uses: projek-xyz/actions/.github/workflows/release.yml@main

  upload:
    name: Upload
    needs: publish
    uses: projek-xyz/actions/.github/workflows/uploads.yml@main
    with:
      workflow_name: Tests
